export const queryKeys = {
  AES_AUTH_TOKEN: 'AES_AUTH_TOKEN',
  LATEST_OBSERVATIONS: 'LATEST_OBSERVATIONS',
  ACCUMULATION_DATA: 'ACCUMULATION_DATA',
  RASTERS_WRF: 'RASTERS_WRF',
  RASTERS_SQPE: 'RASTERS_SQPE',
  RASTERS_ACUM: 'RASTERS_ACUM',
  STATIONS: 'STATIONS',
  STREAM_LEVEL: 'STREAM_LEVEL',
};
